account/urls.py
from django.urls import path, include
from account.views import login, logout, profil, register, register_admin, register_dokter, register_pasien

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    path('register/admin/', register_admin, name='register_admin'),
    path('register/dokter/', register_dokter, name='register_dokter'),
    path('register/pasien/', register_pasien, name='register_pasien'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profil/', profil, name='profil')
]

basdat59/urls.py
from django.contrib import admin
from django.urls import path, include
from basdat59.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('account/', include("account.urls")),
    path('poliklinik/', include("poliklinik.urls")),
    path('', include('resep_obat.urls')),
    path('rs_cabang/', include('rs_cabang.urls')),
    path('sesi_konsultasi/', include('sesi_konsultasi.urls')),
    path('tindakan/', include('tindakan.urls')),
    path('transaksi/', include('transaksi.urls'))
]

poliklinik/urls.py
from django.urls import path
from poliklinik.views import *

app_name = 'poliklinik'

urlpatterns = [
    path('layanan/buat/', buat_layanan_poliklinik, name='buat_layanan'),
    path('layanan/daftar', daftar_layanan_poliklinik, name='daftar_layanan'),
    path('layanan/update/', update_layanan_poliklinik, name='update_layanan'),
    path('layanan/delete/', delete_layanan_poliklinik, name='delete_layanan'),
    path('jadwal/daftar', daftar_jadwal_poliklinik, name='daftar_jadwal'),
    path('jadwal/update/', update_jadwal_poliklinik, name='update_jadwal'),
    path('jadwal/delete/', delete_jadwal_poliklinik, name='delete_jadwal')
]

poliklinik/models.py
from django.db import models

# Create your models here.

poliklinik/forms.py
from django import forms
from django.forms import formset_factory
from django.db import connection

def fetch_to_choices(cursor_fetch):
    choices = []
    choices.append(("-", "-"))
    for item in cursor_fetch:
        choice = (item[0], item[0])
        choices.append(choice)
    return choices

def get_kode_rs():
    with connection.cursor() as cursor:
        cursor.execute('select kode_rs from medikago.rs_cabang')
        query = cursor.fetchall()
        cursor.close()
    return fetch_to_choices(query)

class LayananPoliklinikForm(forms.Form):
    attrs = {'class': 'form-control'}
    kode_rs_choices = get_kode_rs()
    
    nama = forms.CharField(label='Nama Layanan', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    deskripsi = forms.CharField(label='Deskripsi', required=False, widget=forms.Textarea(attrs=attrs))
    kode_rs_cabang = forms.CharField(label='Kode RS', required=True, widget=forms.Select(choices=kode_rs_choices, attrs=attrs))

class UpdateLayananForm(forms.Form):
    attrs = {'class': 'form-control'}
    kode_rs_choices = get_kode_rs()
    
    id_poliklinik = forms.CharField(label='ID Poliklinik', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    nama = forms.CharField(label='Nama Layanan', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    deskripsi = forms.CharField(label='Deskripsi', required=False, widget=forms.Textarea(attrs=attrs))
    kode_rs_cabang = forms.CharField(label='Kode RS', required=True, widget=forms.Select(choices=kode_rs_choices, attrs=attrs))

    def edit(self, commit=True, id_poliklinik=None):
        if not id_poliklinik:
            return
        
        id_poliklinik = self.cleaned_data.get('id_poliklinik')
        nama = self.cleaned_data.get('nama')
        deskripsi = self.cleaned_data.get('deskripsi')
        kode_rs_cabang = self.cleaned_data.get('kode_rs_cabang')

        with connection.cursor() as cursor:
            cursor.execute('update medikago.layanan_poliklinik set kode_rs_cabang=%s, nama=%s, deskripsi=%s where id_poliklinik=%s',
                            [kode_rs_cabang, nama, deskripsi, id_poliklinik])
            cursor.close()

class UpdateJadwalForm(forms.Form):
    attrs = {'class': 'form-control'}

    id_jadwal_poliklinik = forms.CharField(label='ID Jadwal Poliklinik', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    hari = forms.CharField(label='Hari', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    waktu_mulai = forms.TimeField(label='Waktu Mulai', required=True, widget=forms.TimeInput(attrs=attrs))
    waktu_selesai = forms.TimeField(label='Waktu Selesai', required=True, widget=forms.TimeInput(attrs=attrs))
    kapasitas = forms.IntegerField(label='Kapasitas', required=True, widget=forms.NumberInput(attrs=attrs))
    id_dokter = forms.CharField(label='ID Dokter', required=True, max_length=50)
    id_poliklinik = forms.CharField(label='ID Poliklinik', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))

    def __init__(self, id_lp, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        with connection.cursor() as cursor:
            query = 'select id_dokter from medikago.dokter_rs_cabang where kode_rs in '
            query += '(select kode_rs_cabang from medikago.layanan_poliklinik where id_poliklinik=%s)'
            cursor.execute(query, [id_lp])
            query = cursor.fetchall()
            cursor.close()
        id_dokter_choices = fetch_to_choices(query)

        attrs = {'class': 'form-control'}
        self.fields['id_dokter'].widget = forms.Select(choices=id_dokter_choices, attrs=attrs)
    
    def edit(self, commit=True, id_jadwal_poliklinik=None):
        if not id_jadwal_poliklinik:
            return
        
        id_jadwal_poliklinik = self.cleaned_data.get('id_jadwal_poliklinik')
        hari = self.cleaned_data.get('hari')
        waktu_mulai = self.cleaned_data.get('waktu_mulai')
        waktu_selesai = self.cleaned_data.get('waktu_selesai')
        kapasitas = self.cleaned_data.get('kapasitas')
        id_dokter = self.cleaned_data.get('id_dokter')
        id_poliklinik = self.cleaned_data.get('id_poliklinik')

        with connection.cursor() as cursor:
            cursor.execute('update medikago.jadwal_layanan_poliklinik set hari=%s, waktu_mulai=%s, waktu_selesai=%s, kapasitas=%s, id_dokter=%s where id_jadwal_poliklinik=%s',
                            [hari, waktu_mulai, waktu_selesai, kapasitas, id_dokter, id_jadwal_poliklinik])
            cursor.close()

rs_cabang/forms.py
from django import forms
from django.db import connection


year_choice = ["{0}".format(year) for year in range(1995, 2031)]


class RSForm(forms.Form):
    attrs = {'class': 'form-control'}

    kode_rs = forms.CharField(label='Kode RS Cabang', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    nama = forms.CharField(label='Nama', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    tanggal_pendirian = forms.DateField(label='Tanggal Pendirian', required=True, widget=forms.SelectDateWidget(attrs=attrs, years=year_choice))
    jalan = forms.CharField(label='Jalan', required=False, widget=forms.TextInput(attrs=attrs))
    nomor = forms.IntegerField(label='Nomor', required=False, widget=forms.NumberInput(attrs=attrs))
    kota = forms.CharField(label='Kota', required=True, widget=forms.TextInput(attrs=attrs))

    def save(self, commit=True):
        kode_rs = self.cleaned_data.get('kode_rs')
        nama = self.cleaned_data.get('nama')
        tanggal_pendirian = self.cleaned_data.get('tanggal_pendirian')
        jalan = self.cleaned_data.get('jalan')
        nomor = self.cleaned_data.get('nomor')
        kota = self.cleaned_data.get('kota')

        # Save to the database postgresql
        with connection.cursor() as pengguna:
            pengguna.execute('insert into rs_cabang values (%s, %s, %s, %s, %s, %s)',
                             [kode_rs, nama, tanggal_pendirian, jalan, nomor, kota])
            pengguna.close()

    def edit(self, commit=True, kode_rs=None):
        if not kode_rs:
            return

        kode_rs = self.cleaned_data.get('kode_rs')
        nama = self.cleaned_data.get('nama')
        tanggal_pendirian = self.cleaned_data.get('tanggal_pendirian').strftime('%Y-%m-%d')
        jalan = self.cleaned_data.get('jalan')
        nomor = self.cleaned_data.get('nomor')
        kota = self.cleaned_data.get('kota')

        with connection.cursor() as save_rs:
            query = 'update medikago.rs_cabang '
            query += 'set nama=%s, tanggal_pendirian=%s, jalan=%s, nomor=%s, kota=%s '
            query += 'where kode_rs=%s'
            save_rs.execute(query, [nama, tanggal_pendirian, jalan, nomor, kota, kode_rs])
            save_rs.close()


# BEGIN UNGU #

def fetch_to_choices(cursor_fetch):
    choices = []
    choices.append(("-", "-"))
    for item in cursor_fetch:
        choice = (item[0], item[0])
        choices.append(choice)
    return choices

def get_kode_rs():
    with connection.cursor() as cursor:
        cursor.execute('select kode_rs from medikago.rs_cabang')
        query = cursor.fetchall()
        cursor.close()
    return fetch_to_choices(query)

def get_id_dokter():
    with connection.cursor() as cursor:
        cursor.execute('select id_dokter from medikago.dokter')
        query = cursor.fetchall()
        cursor.close()
    return fetch_to_choices(query)

class DaftarkanDokterForm(forms.Form):
    attrs = {'class': 'form-control'}

    kode_rs_choices = get_kode_rs()
    id_dokter_choices = get_id_dokter()

    kode_rs = forms.CharField(label='Kode RS', required=True, widget=forms.Select(choices=kode_rs_choices, attrs=attrs))
    id_dokter = forms.CharField(label='ID Dokter', required=True, widget=forms.Select(choices=id_dokter_choices, attrs=attrs))

    def save(self, commit=True):
        kode_rs = self.cleaned_data.get('kode_rs')
        id_dokter = self.cleaned_data.get('id_dokter')

        with connection.cursor() as cursor:
            cursor.execute('insert into medikago.dokter_rs_cabang values (%s, %s)',
                             [id_dokter, kode_rs])
            cursor.close()
    
    def edit(self, commit=True, id_dokter_old=None, kode_rs_old=None):
        if not (id_dokter_old or kode_rs_old):
            return
        
        kode_rs = self.cleaned_data.get('kode_rs')
        id_dokter = self.cleaned_data.get('id_dokter')

        with connection.cursor() as cursor:
            cursor.execute('update medikago.dokter_rs_cabang set id_dokter=%s, kode_rs=%s where id_dokter=%s and kode_rs=%s', 
                            [id_dokter, kode_rs, id_dokter_old, kode_rs_old])
            cursor.close()

# END UNGU #


KODE_RS_CHOICES = [
    ('RS1', 'RS1'),
    ('RS2', 'RS2'),
    ('RS3', 'RS3'),
    ('RS4', 'RS4'),
    ('RS5', 'RS5')
]

# ID_DOKTER_CHOICES = [
#     ('DOK1', 'DOK1'),
#     ('DOK2', 'DOK2'),
#     ('DOK3', 'DOK3'),
#     ('DOK4', 'DOK4'),
#     ('DOK5', 'DOK5'),
#     ('DOK6', 'DOK6'),
#     ('DOK7', 'DOK7'),
#     ('DOK8', 'DOK8'),
#     ('DOK9', 'DOK9')
# ]

NOMOR_PEGAWAI_CHOICES = [
    ('8ac3c689-74a0-4953-85c6-f45aacead6e2', 'f45aacead6e2'),
    ('e16a9d1a-2141-4470-bb8a-855fbabd36fc', '855fbabd36fc'),
    ('71521487-1c57-4c7e-ac31-d08cc83005b9', 'd08cc83005b9')
]

def get_nomor_pegawai():
    with connection.cursor() as cursor:
        query = "select nomor_pegawai from medikago.administrator"
        cursor.execute(query)
        rows = cursor.fetchall()
        cursor.close()
    
    #print(rows)
    if rows is None:
        print("None")
    return [tuple((item[0], item[0]))
    for item in rows]

def get_kode_rs():
    with connection.cursor() as cursor:
        query = "select kode_rs from medikago.rs_cabang"
        cursor.execute(query)
        rows = cursor.fetchall()
        cursor.close()

    #print(rows)
    if rows is None:
        print("None")
    return [tuple((item[0], item[0]))
    for item in rows]
  

class DaftarkanAdminForm(forms.Form):
    attrs = {'class': 'form-control'}

    daftar_pegawai = get_nomor_pegawai()
    daftar_rs_cabang = get_kode_rs()

    #def __init__(self, data=None, *args, **kwargs):
    #    super(DaftarkanAdminForm, self).__init__(*args, **kwargs)
    #    if data:
    #        self.fields['nomor_pegawai'] = forms.ChoiceField(label="Nomor Pegawai", required=True, choices=data[0])
    #        self.fields['kode_rs'] = forms.ChoiceField(label="Kode RS", required=True, choices=data[1])

    nomor_pegawai = forms.ChoiceField(label='Nomor Pegawai', required=True, choices=daftar_pegawai)
    kode_rs = forms.ChoiceField(label="Kode RS", required=True, choices=daftar_rs_cabang)

    #print(daftar_pegawai)
    #print(daftar_rs_cabang)

    def edit(self, commit=True):
        nomor_pegawai = self.cleaned_data.get('nomor_pegawai')
        kode_rs = self.cleaned_data.get('kode_rs')

        print(kode_rs)

        with connection.cursor() as edit_admin:
            query = "update medikago.administrator "
            query += "set kode_rs = %s where nomor_pegawai = %s"
            edit_admin.execute(query, [kode_rs, nomor_pegawai])
            edit_admin.close()

poliklinik/templates/poliklinik/buat_layanan.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Buat Layanan Poliklinik</h2>
    </div>
    <div>
        {% if request.session.user.role == 'Administrator' %}
        <form method='POST'>
            {% csrf_token %}
            <div class='form-group'>
                <b>{{ form.nama.label_tag }}</b>
                <div>
                    {{ form.nama }}
                </div>
            </div>
            <div class='form-group'>
                <b>{{ form.deskripsi.label_tag }}</b>
                <div>
                    {{ form.deskripsi }}
                </div>
            </div>
            <div class='form-group'>
                <b>{{ form.kode_rs_cabang.label_tag }}</b>
                <div name="kode_rs_cabang">
                    {{ form.kode_rs_cabang }}
                </div>
            </div>
            <div class='form-group'>
                <div class='d-flex justify-content-between'>
                    <b><label for="daftar_jadwal">Daftar Jadwal:</label></b>
                    <a href="javascript:void(0);" class="add_button" title="Add field"><button type="button"
                            class="btn btn-primary"><b>+</b></button></a>
                </div>

                <div class='d-flex flex-column' id='daftar_jadwal'>
                    <div class="d-flex my-2" style="display: none;">
                        <input type="text" name="hari[]" class="form-control mx-1" maxlength="50" placeholder="Hari"
                            required="">
                        <label for="jam_mulai">from:</label><input id="jam_mulai" type="time" name="jam_mulai[]"
                            class="form-control mx-1" required="">
                        <label for="jam_selesai">until:</label><input type="time" id="jam_selesai" name="jam_selesai[]"
                            class="form-control mx-1" required="">
                        <input type="number" name="kapasitas[]" class="form-control mx-1" min="1" max="30"
                            placeholder="Kapasitas" required="">
                        <a href="javascript:void(0);" class="remove_button ml-1">
                            <button type="button" class="btn btn-danger">
                                <b>X</b>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <div>
                <span style="color: #dc3545;">{{ error }}</span>
            </div>
            <button type="submit" class="btn btn-outline-primary my-3">Buat</button>
        </form>
        {% else %}
        <div>
            <span style="color: #dc3545;">Mohon maaf, Anda tidak bisa mengakses halaman ini.</span>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

{% block script %}
<script type="text/javascript">
    $(document).ready(function () {
        var maxField = 10;
        var addButton = $('.add_button');
        var wrapper = $('#daftar_jadwal');
        var fieldHTML =
            '<div class="d-flex my-2" style="display: none;"><input type="text" name="hari[]" class="form-control mx-1" maxlength="50" placeholder="Hari" required=""><label for="jam_mulai">from:</label><input id="jam_mulai" type="time" name="jam_mulai[]" class="form-control mx-1" required=""><label for="jam_selesai">until:</label><input type="time" id="jam_selesai" name="jam_selesai[]" class="form-control mx-1" required=""><input type="number" name="kapasitas[]" class="form-control mx-1" min="1" max="30" placeholder="Kapasitas" required=""><a href="javascript:void(0);" class="remove_button ml-1"><button type="button" class="btn btn-danger"><b>X</b></button></a></div>';
        var x = 0;

        $(addButton).click(function () {
            if (x < maxField) {
                x++;
                $(fieldHTML).appendTo(wrapper).fadeIn();
            } else(
                alert("Terlalu banyak. 10 aja cukup. :)")
            )
        });

        $(wrapper).on('click', '.remove_button', function (e) {
            e.preventDefault();
            $(this).parent('div').fadeOut(300, function () {
                $(this).remove()
            })
            x--;
        });
    });
</script>
{% endblock script %}

poliklinik/templates/poliklinik/daftar_jadwal.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Daftar Jadwal Poliklinik</h2>
    </div>
    <div>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ID Jadwal Poliklinik</th>
                    <th scope="col">Hari</th>
                    <th scope="col">Waktu Mulai</th>
                    <th scope="col">Waktu Selesai</th>
                    <th scope="col">Kapasitas</th>
                    <th scope="col">ID Dokter</th>
                    <th scope="col">ID Poliklinik</th>
                    {% if request.session.user.role == 'Administrator' %}
                    <th scope="col">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for jadwal in daftar_jadwal %}
                <tr>
                    <td>{{ jadwal.id_jadwal_poliklinik }}</td>
                    <td>{{ jadwal.hari }}</td>
                    <td>{{ jadwal.waktu_mulai }}</td>
                    <td>{{ jadwal.waktu_selesai }}</td>
                    <td>{{ jadwal.kapasitas }}</td>
                    <td>{{ jadwal.id_dokter }}</td>
                    <td>{{ jadwal.id_poliklinik }}</td>
                    {% if request.session.user.role == 'Administrator' %}
                    <td class='align-middle'>
                        <div class='d-flex justify-content-center'>
                            <div class='mr-1'>
                                <form action="{% url 'poliklinik:update_jadwal' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="id_jadwal_poliklinik" value="{{ jadwal.id_jadwal_poliklinik }}" hidden>
                                    <input type="hidden" name="id_poliklinik" value="{{ jadwal.id_poliklinik }}" hidden>
                                    <input type="hidden" name="edit" value="true" hidden>
                                    <button type="submit" class="btn btn-primary" title="Update">Update</button>
                                </form>
                            </div>
                            <div>
                                <form action="{% url 'poliklinik:delete_jadwal' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="id_jadwal_poliklinik" value="{{ jadwal.id_jadwal_poliklinik }}" hidden>
                                    <input type="hidden" name="id_poliklinik" value="{{ jadwal.id_poliklinik }}" hidden>
                                    <button type="submit" class="btn btn-outline-danger" title="Delete">Delete</button>
                                </form>
                            </div>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

poliklinik/templates/poliklinik/daftar_layanan.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Daftar Layanan Poliklinik</h2>
    </div>
    <div>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ID Layanan Poliklinik</th>
                    <th scope="col">Kode RS Cabang</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Jadwal Poliklinik</th>
                    {% if request.session.user.role == 'Administrator' %}
                    <th scope="col">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for layanan in daftar_layanan %}
                <tr>
                    <td>{{ layanan.id_poliklinik }}</td>
                    <td>{{ layanan.kode_rs_cabang }}</td>
                    <td>{{ layanan.nama }}</td>
                    <td>{{ layanan.deskripsi }}</td>
                    <td class="align-middle">
                        <div class='d-flex justify-content-center'>
                            <form action="{% url 'poliklinik:daftar_jadwal' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="id_poliklinik" value="{{ layanan.id_poliklinik }}" hidden>
                                <button type="submit" class="btn btn-info" title="Update">Info Jadwal</button>
                            </form>
                        </div>
                    </td>
                    {% if request.session.user.role == 'Administrator' %}
                    <td class='align-middle'>
                        <div class='d-flex justify-content-center'>
                            <div class='mr-1'>
                                <form action="{% url 'poliklinik:update_layanan' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="id_poliklinik" value="{{ layanan.id_poliklinik }}" hidden>
                                    <input type="hidden" name="edit" value="true" hidden>
                                    <button type="submit" class="btn btn-primary" title="Update">Update</button>
                                </form>
                            </div>
                            <div>
                                <form action="{% url 'poliklinik:delete_layanan' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="id_poliklinik" value="{{ layanan.id_poliklinik }}" hidden>
                                    <button type="submit" class="btn btn-outline-danger" title="Delete">Delete</button>
                                </form>
                            </div>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

poliklinik/templates/poliklinik/update_jadwal.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Update Jadwal Poliklinik</h2>
    </div>
    <div>
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <b>{{ field.label_tag }}</b>
                <div class="d-flex">
                    {% if 'Poliklinik' in field.label %}
                    <input type="text" name="{{ field.name }}" value="{{ field.value }}" class="form-control" maxlength="50" required="" id="{{ field.auto_id }}" disabled>
                    {% else %}
                    {{ field }}
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <input type="hidden" name="id_jadwal_poliklinik" value="{{ id_jadwal_poliklinik }}" hidden>
            <input type="hidden" name="id_poliklinik" value="{{ id_poliklinik }}" hidden>
            <input type="hidden" name="edit" value="false" hidden>
            <div>
                <div id="message"></div>
                <button type="submit" class="btn btn-outline-primary my-3" id="update_button">Update</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function() {
        $("#id_id_dokter").change(function(event) {
            $("#message").html("");
            
            let id_dokter = $(this).val();
            
            if (id_dokter == "-") {
                $("#message").html("ID Dokter '-' tidak valid.");
                $("#message").css('color', '#dc3545');
                $("#update_button").attr("disabled", "True");
            } else {
                $("#id_kode_rs").attr("disabled", "True");
                $("#update_button").removeAttr("disabled");
            }
        });
    });
</script>
{% endblock script %}

poliklinik/templates/poliklinik/update_layanan.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Update Layanan Poliklinik</h2>
    </div>
    <div>
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <b>{{ field.label_tag }}</b>
                <div class="d-flex">
                    {% if 'ID' in field.label %}
                    <input type="text" name="{{ field.name }}" value="{{ field.value }}" class="form-control" maxlength="50" required="" id="{{ field.auto_id }}" disabled>
                    {% else %}
                    {{ field }}
                    {% endif %}
                </div>
                {% if field.errors %}
                <strong style="color: red;">{{ field.errors }}</strong>
                {% endif %}
            </div>
            {% endfor %}
            <input type="hidden" name="id_poliklinik" value="{{ id_poliklinik }}" hidden>
            <input type="hidden" name="edit" value="false" hidden>
            <div>
                <div id="message"></div>
                <button type="submit" class="btn btn-outline-primary my-3" id="update_button">Update</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function() {
        $("#id_kode_rs_cabang").change(function(event) {
            $("#message").html("");
            
            let kode_rs_cabang = $(this).val();

            if (kode_rs_cabang == "-") {
                $("#message").html("Kode RS '-' tidak valid.");
                $("#message").css('color', '#dc3545');
                $("#update_button").attr("disabled", "True");
            } else {
                $("#update_button").removeAttr("disabled");
            }
        })
    });
</script>
{% endblock script %}