account/urls.py
from django.urls import path, include
from account.views import login, logout, profil, register, register_admin, register_dokter, register_pasien

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    path('register/admin/', register_admin, name='register_admin'),
    path('register/dokter/', register_dokter, name='register_dokter'),
    path('register/pasien/', register_pasien, name='register_pasien'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profil/', profil, name='profil')
]

basdat59/urls.py
from django.contrib import admin
from django.urls import path, include
from basdat59.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('account/', include("account.urls")),
    path('poliklinik/', include("poliklinik.urls")),
    path('', include('resep_obat.urls')),
    path('rs_cabang/', include('rs_cabang.urls')),
    path('sesi_konsultasi/', include('sesi_konsultasi.urls')),
    path('tindakan/', include('tindakan.urls')),
    path('transaksi/', include('transaksi.urls'))
]

resep_obat/urls.py
from django.urls import path
from resep_obat.views import buat_obat, buat_resep, daftar_obat, daftar_resep, update_obat, delete_obat, delete_resep, edit_resep

app_name = 'resep_obat'

urlpatterns = [
    path('obat/buat/', buat_obat, name='buat_obat'),
    path('obat/daftar/', daftar_obat, name='daftar_obat'),
    path('obat/update', update_obat, name='update_obat'),
    path('obat/delete/', delete_obat, name='delete_obat'),
    path('resep/buat/', buat_resep, name='buat_resep'),
    path('resep/daftar/', daftar_resep, name='daftar_resep'),
    path('resep/delete/', delete_resep, name='delete_resep'),
    path('resep/edit/', edit_resep, name='edit_resep')
]

resep_obat/models.py
from django.db import models

# Create your models here.

resep_obat/forms.py
from django import forms
from django.db import connection

class CreateObatForm(forms.Form):
    attrs = {'class' : 'form-control'}

    kode = forms.CharField(label="Kode Obat", required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    stok = forms.IntegerField(label="Stok", required=True, min_value=0, widget=forms.NumberInput(attrs=attrs))
    harga = forms.IntegerField(label="Harga", required=True, min_value=0, widget=forms.NumberInput(attrs=attrs))
    komposisi = forms.CharField(label="Komposisi", widget=forms.Textarea(attrs=attrs))
    bentuk_sediaan = forms.CharField(label="Bentuk Sediaan", required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    merk_dagang = forms.CharField(label="Merk Dagang", required=True, max_length=50, widget=forms.TextInput(attrs=attrs))

    def is_valid(self):
        valid = super(CreateObatForm, self).is_valid()

        if not valid:
            return valid

        return True

    def save(self, commit=True):
        kode = self.cleaned_data.get('kode')
        stok = self.cleaned_data.get('stok')
        harga = self.cleaned_data.get('harga')
        komposisi = self.cleaned_data.get('komposisi')
        bentuk_sediaan = self.cleaned_data.get('bentuk_sediaan')
        merk_dagang = self.cleaned_data.get('merk_dagang')

        with connection.cursor() as obat:
            obat.execute('insert into medikago.obat values (%s, %s, %s, %s, %s, %s)',
                        [kode, stok, harga, komposisi, bentuk_sediaan, merk_dagang])
            obat.close()
    
    def edit(self, commit=True, kode=None):
        if not kode:
            return
        
        kode = self.cleaned_data.get('kode')
        stok = self.cleaned_data.get('stok')
        harga = self.cleaned_data.get('harga')
        komposisi = self.cleaned_data.get('komposisi')
        bentuk_sediaan = self.cleaned_data.get('bentuk_sediaan')
        merk_dagang = self.cleaned_data.get('merk_dagang')

        with connection.cursor() as save_obat:
            query = 'update medikago.obat '
            query += 'set kode=%s, stok=%s, harga=%s, komposisi=%s, bentuk_sediaan=%s, merk_dagang=%s '
            query += 'where kode=%s'
            save_obat.execute(query, [kode, stok, harga, komposisi, bentuk_sediaan, merk_dagang, kode])
            save_obat.close()


RESEP_CHOICES = [
    ('20d68445-0041-4775-8ef4-713fda501668','713fda501668'),
    ('dddeeeef-85ff-4708-9787-d521aec86cdb', 'd521aec86cdb'),
    ('1933e7f6-1487-4e79-8912-d9cb01a5f8ad', 'd9cb01a5f8ad')
]

TRANSAKSI_CHOICES = [
    ('1','1'),
    ('2','2'),
    ('3','3')
]

OBAT_CHOICES = [
    ('53746-206', '53746-206'),
    ('43598-218', '43598-218'),
    ('21695-671', '21695-671')
]

def get_id_transaksi():
    with connection.cursor() as cursor:
        cursor.execute('select id_transaksi from medikago.transaksi')
        rows = cursor.fetchall()
        cursor.close()
    
    return [tuple((item[0], item[0]))
            for item in rows]
            
def get_id_konsultasi():
    with connection.cursor() as cursor:
        cursor.execute('select id_konsultasi from medikago.sesi_konsultasi')
        rows = cursor.fetchall()
        cursor.close()
    
    return [tuple((item[0], item[0]))
            for item in rows]

def get_kode_obat():
    with connection.cursor() as cursor:
        cursor.execute('select kode from medikago.obat')
        rows = cursor.fetchall()
        cursor.close()
    
    return [tuple((item[0], item[0]))
            for item in rows]

def nomor_resep_generator():
    with connection.cursor() as get_nomor_resep:
        query = "select no_resep from "
        query += "medikago.resep order by "
        query += "nullif(regexp_replace(no_resep, '\D', '', 'g'), '')::int desc limit 1"
        get_nomor_resep.execute(query)
        row = get_nomor_resep.fetchone()
        get_nomor_resep.close()
    
    last_nomor = int(row[0]) if (row is not None) else None
   
    if last_nomor is None:
        return str(1)
    
    return str(last_nomor + 1)

class CreateResepObat(forms.Form):

    
    attrs = {'class' : 'form-control'}

    daftar_transaksi = get_id_transaksi()
    daftar_konsultasi = get_id_konsultasi()
    daftar_kode_obat = get_kode_obat()

    id_konsultasi = forms.ChoiceField(label="ID Konsultasi", required=True, choices=daftar_konsultasi)
    id_transaksi = forms.ChoiceField(label="ID Transaksi", required=True, choices=daftar_transaksi)
    daftar_obat = forms.MultipleChoiceField(label="Daftar Kode Obat", required=True, choices=daftar_kode_obat)

    def save(self, commit=True):
        no_resep = nomor_resep_generator()
        id_konsultasi = self.cleaned_data.get('id_konsultasi')
        total_harga = None
        id_transaksi = self.cleaned_data.get('id_transaksi')
        daftar_obat = self.cleaned_data.get('daftar_obat')

        print(daftar_obat)

        with connection.cursor() as resep:
            resep.execute('insert into medikago.resep values(%s, %s, %s, %s)',
                            [no_resep, id_konsultasi, 0, id_transaksi])
            for obat in daftar_obat:
                resep.execute('insert into medikago.daftar_obat values(%s, %s, %s, %s)',
                            [no_resep, obat, '-', '-'])
            resep.close()
    
    def edit(self, commit=True, no_resep=None):
        if not no_resep:
            return

        id_konsultasi = self.cleaned_data.get('id_konsultasi')
        total_harga = None
        id_transaksi = self.cleaned_data.get('id_transaksi')
        daftar_obat = self.cleaned_data.get('daftar_obat')

        print(daftar_obat)

        with connection.cursor() as resep:
            resep.execute('delete from medikago.daftar_obat where no_resep=%s', [no_resep])
            resep.execute('update medikago.resep set id_konsultasi=%s, id_transaksi=%s, total_harga=%s where no_resep=%s',
                            [id_konsultasi, id_transaksi, 0, no_resep])
            for obat in daftar_obat:
                resep.execute('insert into medikago.daftar_obat values(%s, %s, %s, %s)',
                            [no_resep, obat, '-', '-'])
            resep.close()

resep_obat/views.py
from django.shortcuts import render, redirect
from django.db import connection
from resep_obat.forms import *

# Create your views here.
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def fetch_obat():
    with connection.cursor() as get_all_obat:
        get_all_obat.execute('select * from medikago.obat')
        result = dictfetchall(get_all_obat)
        get_all_obat.close()
    return result

def fetch_resep():
    with connection.cursor() as get_all_resep:
        query = ('select a.no_resep, a.id_konsultasi, a.total_harga, a.id_transaksi, ')
        query += ("STRING_AGG(c.kode_obat, ', ') kode_obat ")
        query += ('from medikago.resep a, medikago.daftar_obat c ')
        query += ('where a.no_resep = c.no_resep ')
        query += ('group by a.no_resep order by a.no_resep desc')
        get_all_resep.execute(query)
        result = dictfetchall(get_all_resep)
        get_all_resep.close()
    return result

def fetch_daftar_obat(no_resep):
    with connection.cursor() as get_all_daftar:
        query = 'select a.merk_dagang from medikago.obat a'
        query += 'join medikago.daftar_obat b on a.kode = b.kode_obat '
        query += 'where b.no_resep = %s'
        get_all_daftar.execute(query, [no_resep])
        result = dictfetchall(get_all_daftar)
        get_all_daftar.close()
    return result

def check_obat_exists(kode):
    with connection.cursor() as obat:
        obat.execute('select kode from medikago.obat where kode = %s', [kode])
        check_kode = obat.fetchone()

        if check_kode:
            return "kode obat sudah terdaftar"
        
        obat.close()
    
    return None


def daftar_obat(request):
    obat_tuple = fetch_obat()

    context = {
        'page_title': 'Daftar Obat',
        'obat_dict': obat_tuple
    }

    return render(request, 'resep_obat/daftar_obat.html', context)

def buat_obat(request):
    form = CreateObatForm
    context = {
        'page_title': 'Buat Obat',
        'form' : form
    }

    if request.method=='POST':
        form = form(request.POST)
        if form.is_valid():
            kode = request.POST.get('kode')
            stok = request.POST.get('stok')
            harga = request.POST.get('harga')
            komposisi = request.POST.get('komposisi')
            bentuk_sediaan = request.POST.get('bentuk_sediaan')
            merk_dagang = request.POST.get('merk_dagang')

            does_obat_exists = check_obat_exists(kode)

            if does_obat_exists is not None:
                context['error'] = does_obat_exists
                return render(request, 'resep_obat/buat_obat.html', context)
            
            form.save()
            context['form'] = form
            return redirect("resep_obat:daftar_obat")

    return render(request, 'resep_obat/buat_obat.html', context)

def update_obat(request):
    if request.method == "GET":
        return redirect('resep_obat:daftar_obat')

    form = CreateObatForm
    
    context = {
        'page_title': 'Update Obat',
        'form' : form
    }

    if request.method == "POST":
        if request.POST.get('edit') == 'true':
            with connection.cursor() as get_obat:
                get_obat.execute('select * from medikago.obat where kode = %s', [request.POST.get('kode')])
                obat_query = get_obat.fetchone()
                get_obat.close()

            obat = {
                'kode' : obat_query[0],
                'stok' : obat_query[1],
                'harga' : obat_query[2],
                'komposisi' : obat_query[3],
                'bentuk_sediaan' : obat_query[4],
                'merk_dagang' : obat_query[5]
            }

            form = form(obat)
            context['form'] = form
            context['kode'] = obat_query[0]

            return render(request, 'resep_obat/update_obat.html', context)
        else:
            form = form(request.POST)
            if form.is_valid():
                
                kode = request.POST.get('kode')
                stok = request.POST.get('stok')
                harga = request.POST.get('harga')
                komposisi = request.POST.get('komposisi')
                bentuk_sediaan = request.POST.get('bentuk_sediaan')
                merk_dagang = request.POST.get('merk_dagang')

                form.edit(kode=request.POST.get('kode'))
                return redirect('resep_obat:daftar_obat')
    
    return render(request, 'resep_obat/update_obat.html', context)

def delete_obat(request):
    if request.method == 'POST':
        kode = request.POST.get('kode')
        if kode:
            with connection.cursor() as delete_obat:
                delete_obat.execute('delete from medikago.obat where kode = %s', [kode])
                delete_obat.close()
    return redirect("resep_obat:daftar_obat")

def daftar_resep(request):
    resep_tuple = fetch_resep()
    
    print(resep_tuple)
    
    context = {
        'page_title': 'Daftar Resep',
        'resep_dict': resep_tuple
    }
    return render(request, 'resep_obat/daftar_resep.html', context)

def buat_resep(request):

    form = CreateResepObat()

    form.fields['id_konsultasi'].widget.choices = get_id_konsultasi()
    form.fields['id_transaksi'].widget.choices = get_id_transaksi()
    form.fields['daftar_obat'].widget.choices = get_kode_obat()

    context = {
        'page_title': 'Buat Resep',
        'form' : form
    }

    if request.method == "POST":
        form = CreateResepObat(request.POST)
        if form.is_valid():
            id_konsultasi = form.cleaned_data.get('id_konsultasi')
            id_transaksi = form.cleaned_data.get('id_transaksi')
            daftar_obat = form.cleaned_data.get('daftar_obat')

            form.save()
            form.fields['id_konsultasi'].widget.choices = get_id_konsultasi()
            form.fields['id_transaksi'].widget.choices = get_id_transaksi()
            form.fields['daftar_obat'].widget.choices = get_kode_obat()
            
        return redirect("resep_obat:daftar_resep")
    
    return render(request, 'resep_obat/buat_resep.html', context)

def edit_resep(request):
    if request.method == 'GET':
        return redirect("resep_obat:daftar_resep")
        
    form = CreateResepObat

    context = {
        'page_title': 'Edit Resep',
        'form' : form
    }

    if request.method == "POST":
        if request.POST.get('edit') == 'true':
            form = form()
            context['form'] = form
            context['no_resep'] = request.POST.get('no_resep')

            return render(request, 'resep_obat/update_resep.html', context)
        else:
            form = form(request.POST)
            if form.is_valid():

                form.edit(no_resep=request.POST.get('no_resep'))
                return redirect('resep_obat:daftar_resep')
    
    return render(request, 'resep_obat/update_resep.html', context)

def delete_resep(request):
    if request.method == 'POST':
        no_resep = request.POST.get('no_resep')
        if no_resep:
            with connection.cursor() as delete_resep:
                delete_resep.execute('delete from medikago.daftar_obat where no_resep=%s', [no_resep])
                delete_resep.execute('delete from medikago.resep where no_resep=%s', [no_resep])
                delete_resep.close()
    return redirect("resep_obat:daftar_resep")

resep_obat/templates/resep_obat/buat_obat.html
{% extends 'basdat59/base.html' %}

{% block content %}
<!-- KUNING -->
<div class='container'>
    <div class='d-flex justify-content-center align-items-center my-3'>
        <div class='d-flex flex-column'>
            <div class='text-center my-3'><h2>Buat Obat</h2></div>
            <div class='container'>
                <form method='POST'>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class='form-group'>
                            <b>{{ field.label_tag }}</b>
                            <div class='d-flex'>
                                {{ field }}
                            </div>
                            {% if field.errors %}
                                <strong style="color: red;">{{ field.errors }}</strong>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary float-right">Submit</button>
                </form>
            </div>
        </div>
    </div>    
</div>
{% endblock content %}

resep_obat/templates/resep_obat/buat_resep.html
{% extends 'basdat59/base.html' %}

{% block content %}
<!-- KUNING -->
<div class='container'>
    <div class='d-flex justify-content-center align-items-center my-3'>
        <div class='d-flex flex-column'>
            <div class='text-center my-3'><h2>Buat Resep</h2></div>
            <div class='container'>
                <form method='POST'>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class='form-group'>
                            <b>{{ field.label_tag }}</b>
                            <div class='d-flex'>
                                {{ field }}
                            </div>
                            {% if field.errors %}
                                <strong style="color: red;">{{ field.errors }}</strong>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary float-right">Submit</button>
                </form>
            </div>
        </div>
    </div>    
</div>
{% endblock content %}

resep_obat/templates/resep_obat/daftar_obat.html
{% extends 'basdat59/base.html' %}

{% block content %}
<!-- KUNING -->
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Daftar Obat</h2>
    </div>
    <div>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Kode</th>
                    <th scope="col">Stok</th>
                    <th scope="col">Harga</th>
                    <th scope="col">Komposisi</th>
                    <th scope="col">Bentuk Sediaan</th>
                    <th scope="col">Merk Dagang</th>
                    {% if request.session.user.role == 'Administrator' %}
                    <th scope="col">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for obat in obat_dict %}
                <tr>
                    <td>{{ obat.kode }}</td>
                    <td>{{ obat.stok }}</td>
                    <td>{{ obat.harga }}</td>
                    <td>{{ obat.komposisi }}</td>
                    <td>{{ obat.bentuk_sediaan }}</td>
                    <td>{{ obat.merk_dagang }}</td>
                    {% if request.session.user.role == 'Administrator' %}
                    <td class='align-middle'>
                            <div class='d-flex justify-content-center'>
                                <div class='mr-1'>
                                    <form action="{% url 'resep_obat:update_obat' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="kode" value="{{ obat.kode }}" hidden>
                                        <input type="hidden" name="edit" value="true" hidden>
                                        <button type="submit" class="btn btn-primary" title="edit">Edit</button>
                                    </form>
                                </div>
                                <div>
                                    <form action="{% url 'resep_obat:delete_obat' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="kode" value="{{ obat.kode }}">
                                        <button type="submit" class="btn btn-danger" title="edit">X</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

resep_obat/templates/resep_obat/daftar_resep.html
{% extends 'basdat59/base.html' %}

{% block content %}
<!-- KUNING -->
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Daftar Resep</h2>
    </div>
    <div>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Nomor Resep</th>
                    <th scope="col">Total Harga</th>
                    <th scope="col">ID Konsultasi</th>
                    <th scope="col">ID Transaksi</th>
                    <th scope="col">Daftar Obat</th>
                    {% if request.session.user.role == 'Administrator' %}
                    <th scope="col">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for resep in resep_dict %}
                <tr>
                    <td>{{ resep.no_resep }}</td>
                    <td>{{ resep.total_harga }}</td>
                    <td>{{ resep.id_konsultasi }}</td>
                    <td>{{ resep.id_transaksi }}</td>
                    <td>{{ resep.kode_obat }}</td>
                    {% if request.session.user.role == 'Administrator' %}
                    <td class='align-middle'>
                            <div class='d-flex justify-content-center'>
                                <div class='mr-1'>
                                    <form action="{% url 'resep_obat:edit_resep' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="no_resep" value="{{ resep.no_resep }}" hidden>
                                        <input type="hidden" name="edit" value="true" hidden>
                                        <button type="submit" class="btn btn-primary" title="update">Update</button>
                                    </form>
                                </div>
                                <div>
                                    <form action="{% url 'resep_obat:delete_resep' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="no_resep" value="{{ resep.no_resep }}">
                                        <button type="submit" class="btn btn-danger" title="edit">X</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

resep_obat/templates/resep_obat/update_obat.html
{% extends 'basdat59/base.html' %}

{% block content %}
<!-- KUNING -->
<div class='container'>
    <div class='d-flex justify-content-center align-items-center my-3'>
        <div class='d-flex flex-column'>
            <div class='text-center my-3'><h2>Update Obat</h2></div>
            <div>
                <form method='POST'>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class='form-group'>
                            <b>{{ field.label_tag }}</b>
                            <div class='d-flex'>
                            {% if 'Kode' in field.label %}
                                <input type="text" name="{{ field.name }}" value="{{ field.value }}" class="form-control" maxlength="50" required="" id="kode" disabled>
                            {% else %}
                                {{ field }}
                            {% endif %}
                            </div>
                            {% if field.errors %}
                                <strong style="color: red;">{{ field.errors }}</strong>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="hidden" name="kode" value="{{ kode }}" hidden>
                    <input type="hidden" name="edit" value="false" hidden>
                    <button type="submit" class="btn btn-primary float-right">Submit</button>
                </form>
            </div>
        </div>
    </div>    
</div>
{% endblock content %}

resep_obat/templates/resep_obat/update_resep.html
{% extends 'basdat59/base.html' %}

{% block content %}
<!-- KUNING -->
<div class='container'>
    <div class='d-flex justify-content-center align-items-center my-3'>
        <div class='d-flex flex-column'>
            <div class='text-center my-3'><h2>Update Resep</h2></div>
            <div class='container'>
                <form method='POST'>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class='form-group'>
                            <b>{{ field.label_tag }}</b>
                            <div class='d-flex'>
                                {{ field }}
                            </div>
                            {% if field.errors %}
                                <strong style="color: red;">{{ field.errors }}</strong>
                            {% endif %}
                        </div>
                    {% endfor %}
                    {% csrf_token %}
                    <input type="hidden" name="no_resep" value="{{ no_resep }}" hidden>
                    <button type="submit" class="btn btn-primary float-right">Submit</button>
                </form>
            </div>
        </div>
    </div>    
</div>
{% endblock content %}