account/urls.py
from django.urls import path, include
from account.views import login, logout, profil, register, register_admin, register_dokter, register_pasien

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    path('register/admin/', register_admin, name='register_admin'),
    path('register/dokter/', register_dokter, name='register_dokter'),
    path('register/pasien/', register_pasien, name='register_pasien'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profil/', profil, name='profil')
]

basdat59/urls.py
from django.contrib import admin
from django.urls import path, include
from basdat59.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('account/', include("account.urls")),
    path('poliklinik/', include("poliklinik.urls")),
    path('', include('resep_obat.urls')),
    path('rs_cabang/', include('rs_cabang.urls')),
    path('sesi_konsultasi/', include('sesi_konsultasi.urls')),
    path('tindakan/', include('tindakan.urls')),
    path('transaksi/', include('transaksi.urls'))
]

poliklinik/urls.py
from django.urls import path
from poliklinik.views import *

app_name = 'poliklinik'

urlpatterns = [
    path('layanan/buat/', buat_layanan_poliklinik, name='buat_layanan'),
    path('layanan/daftar', daftar_layanan_poliklinik, name='daftar_layanan'),
    path('layanan/update/', update_layanan_poliklinik, name='update_layanan'),
    path('layanan/delete/', delete_layanan_poliklinik, name='delete_layanan'),
    path('jadwal/daftar', daftar_jadwal_poliklinik, name='daftar_jadwal'),
    path('jadwal/update/', update_jadwal_poliklinik, name='update_jadwal'),
    path('jadwal/delete/', delete_jadwal_poliklinik, name='delete_jadwal')
]

rs_cabang/urls.py
from django.urls import path
from rs_cabang.views import buat_rs, daftar_admin, daftar_dokter, daftar_rs, daftarkan_dokter, delete_rs, update_dokter, delete_dokter, update_rs

app_name = 'rs_cabang'

urlpatterns = [
    path('buat/', buat_rs, name='buat_rs'),
    path('daftar/', daftar_rs, name='daftar_rs'),
    path('update/', update_rs, name='update_rs'),
    path('delete/', delete_rs, name='delete_rs'),
    path('dokter/daftarkan/', daftarkan_dokter, name='daftarkan_dokter'),
    path('dokter/daftar/', daftar_dokter, name='daftar_dokter'),
    path('dokter/update/', update_dokter, name='update_dokter'),
    path('dokter/delete/', delete_dokter, name='delete_dokter'),
    path('admin/daftar/', daftar_admin, name='daftar_admin')
]

tindakan/urls.py
from django.urls import path
from tindakan.views import buat_tindakan, buat_tindakan_poliklinik, daftar_tindakan, daftar_tindakan_poliklinik

app_name = 'tindakan'

urlpatterns = [
    path('buat/', buat_tindakan, name='buat_tindakan'),
    path('daftar/', daftar_tindakan, name='daftar_tindakan'),
    path('poliklinik/buat/', buat_tindakan_poliklinik, name='buat_tindakan_poliklinik'),
    path('poliklinik/daftar', daftar_tindakan_poliklinik, name='daftar_tindakan_poliklinik')
]

transaksi/urls.py
from django.urls import path
from transaksi.views import daftar_transaksi, buat_transaksi, update_transaksi, delete_transaksi

app_name = 'transaksi'

urlpatterns = [
    path('buat/', buat_transaksi, name='buat_transaksi'),
    path('daftar/', daftar_transaksi, name='daftar_transaksi'),
    path('update/', update_transaksi, name='update_transaksi'),
    path('delete/', delete_transaksi, name='delete_transaksi')
]

basdat59/views.py
from django.shortcuts import render

def index(request):

    context = {
        'page_title':'Home'
    }

    return render(request, 'basdat59/home.html', context)
    

basdat59/templates/basdat59/snippets/bootstrap-css.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

basdat59/templates/basdat59/snippets/bootstrap-js.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

basdat59/templates/basdat59/snippets/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <div class="nav navbar-nav navbar-center">
    <a class="navbar-brand mx-auto neon" href="{% url 'home' %}">
      BasDat 59 - MedikaGo!
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  </div>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    {% if request.session.user.role %}
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="{% url 'account:profil' %}">Profil</a></li>
          <li class="dropdown-submenu">
            <a class="dropdown-item dropdown-toggle" href="#">Sesi Konsultasi</a>
            <ul class="dropdown-menu">
              {% if request.session.user.role == 'Administrator' %}
              <li><a class="dropdown-item" href="{% url 'sesi_konsultasi:buat_sesi' %}">Buat Sesi Konsultasi</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'sesi_konsultasi:daftar_sesi' %}">Daftar Sesi Konsultasi</a>
              </li>
            </ul>
          </li>
          <li class="dropdown-submenu">
            <a class="dropdown-item dropdown-toggle" href="#">Poliklinik</a>
            <ul class="dropdown-menu">
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'poliklinik:buat_layanan' %}">Buat Layanan Poliklinik</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'poliklinik:daftar_layanan' %}">Daftar Layanan Poliklinik</a>
              </li>
              <li><a class="dropdown-item" href="{% url 'poliklinik:daftar_jadwal' %}">Daftar Jadwal Poliklinik</a></li>
            </ul>
          </li>
          <li class="dropdown-submenu">
            <a class="dropdown-item dropdown-toggle" href="#">RS Cabang</a>
            <ul class="dropdown-menu">
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'rs_cabang:buat_rs' %}">Buat RS Cabang</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'rs_cabang:daftar_rs' %}">Daftar RS Cabang</a></li>
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'rs_cabang:daftarkan_dokter' %}">Daftarkan Dokter</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'rs_cabang:daftar_dokter' %}">Daftar Dokter</a></li>
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'rs_cabang:daftar_admin' %}">Daftar Administrator</a></li>
              {% endif %}
            </ul>
          </li>
          <li class="dropdown-submenu">
            <a class="dropdown-item dropdown-toggle" href="#">Tindakan</a>
            <ul class="dropdown-menu">
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'tindakan:buat_tindakan' %}">Buat Tindakan</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'tindakan:daftar_tindakan' %}">Daftar Tindakan</a></li>
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'tindakan:buat_tindakan_poliklinik' %}">Buat Tindakan
                  Poliklinik</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'tindakan:daftar_tindakan_poliklinik' %}">Daftar Tindakan
                  Polklinik</a></li>
            </ul>
          </li>
          <li class="dropdown-submenu">
            <a class="dropdown-item dropdown-toggle" href="#">Resep dan Obat</a>
            <ul class="dropdown-menu">
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'resep_obat:buat_resep' %}">Buat Resep</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'resep_obat:daftar_resep' %}">Daftar Resep</a></li>
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'resep_obat:buat_obat' %}">Buat Obat</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'resep_obat:daftar_obat' %}">Daftar Obat</a></li>
            </ul>
          </li>
          {% if request.session.user.role != "Administrator" %}
          <li><a class="dropdown-item" href="{% url 'poliklinik:daftar_layanan' %}">Daftar Layanan</a></li>
          {% endif %}
          <li class="dropdown-submenu">
            <a class="dropdown-item dropdown-toggle" href="#">Transaksi</a>
            <ul class="dropdown-menu">
              {% if request.session.user.role == "Administrator" %}
              <li><a class="dropdown-item" href="{% url 'transaksi:buat_transaksi' %}">Buat Transaksi</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'transaksi:daftar_transaksi' %}">Daftar Transaksi</a></li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
    {% endif %}
    <ul class='navbar-nav ml-auto'>
      {% if request.session.user %}
      <li class='nav-item my-1' style="margin-right:10px"><span>Halo, </span><span>{{ request.session.user.nama_lengkap }}</span></li>
      {% endif %}
      {% if not request.session.user.role %}
      <li class='nav-item my-1'><a href="{% url 'account:login' %}" class="btn btn-outline-info my-2 my-sm-0"
          style="margin-right: 10px;">Login</a></li>
      <li class='nav-item my-1'><a href="{% url 'account:register' %}" class="btn btn-outline-info my-2 my-sm-0"
          style="margin-right: 10px;">Register</a> </li>
      {% endif %}      
      {% if request.session.user.role %}
      <li class='nav-item'><a href="{% url 'account:logout' %}" class="btn btn-outline-danger my-2 my-sm-0">Logout</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

basdat59/templates/basdat59/snippets/styles.html
        <style>
            html, body {
                height : 100%;
                font-family: 'Fredoka One', cursive;
                color : #455A64;
                background-color:  rgb(181, 207, 219);
            }
            
            .full-height {
                height : 100%;
            }

            .jumbotron{
                height: 100vh;
                background-color: rgb(181, 207, 219);
            }
            
            .neon {
                position: relative;
                padding: 10px 20px;
                color: #2196f3;
                letter-spacing: 2px;
                text-decoration: none;
                overflow: hidden;
                transition: 0.2s;
            }

            .neon span {
                position: absolute;
                display: block;
            }

            .neon span:nth-child(1) {
                top: 0;
                left: -100%;
                width: 100%;
                height: 2px;
                background: linear-gradient(90deg,transparent,#2196f3)
            }

            .neon:hover span:nth-child(1) {
                left: 100%;
                transition: 1s;
            }

            .neon span:nth-child(3) {
                bottom: 0;
                right: -100%;
                width: 100%;
                height: 2px;
                background: linear-gradient(270deg,transparent,#2196f3)
            }

            .neon:hover span:nth-child(3) {
                right: 100%;
                transition: 1s;
                transition-delay: .5s;
            }

            .neon span:nth-child(2) {
                top: -100%;
                right: 0;
                width: 2px;
                height: 100%;
                background: linear-gradient(180deg,transparent,#2196f3)
            }

            .neon:hover span:nth-child(2) {
                top: 100%;
                transition: 1s;
                transition-delay: .25s;
            }

            .neon span:nth-child(4) {
                bottom: -100%;
                left: 0;
                width: 2px;
                height: 100%;
                background: linear-gradient(360deg,transparent,#2196f3)
            }

            .neon:hover span:nth-child(4) {
                bottom: 100%;
                transition: 1s;
                transition-delay: .75s;
            }

            .dropdown-submenu {
                position: relative;
            }

            .dropdown-submenu a::after {
                transform: rotate(-90deg);
                position: absolute;
                right: 6px;
                top: .8em;
            }

            .dropdown-submenu .dropdown-menu {
                top: 0;
                left: 100%;
                margin-left: .1rem;
                margin-right: .1rem;
            }
            

        </style>