account/urls.py
from django.urls import path, include
from account.views import login, logout, profil, register, register_admin, register_dokter, register_pasien

app_name = 'account'

urlpatterns = [
    path('register/', register, name='register'),
    path('register/admin/', register_admin, name='register_admin'),
    path('register/dokter/', register_dokter, name='register_dokter'),
    path('register/pasien/', register_pasien, name='register_pasien'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profil/', profil, name='profil')
]

basdat59/urls.py
from django.contrib import admin
from django.urls import path, include
from basdat59.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('account/', include("account.urls")),
    path('poliklinik/', include("poliklinik.urls")),
    path('', include('resep_obat.urls')),
    path('rs_cabang/', include('rs_cabang.urls')),
    path('sesi_konsultasi/', include('sesi_konsultasi.urls')),
    path('tindakan/', include('tindakan.urls')),
    path('transaksi/', include('transaksi.urls'))
]

rs_cabang/urls.py
from django.urls import path
from rs_cabang.views import buat_rs, daftar_admin, daftar_dokter, daftar_rs, daftarkan_dokter, delete_rs, update_dokter, delete_dokter, update_rs

app_name = 'rs_cabang'

urlpatterns = [
    path('buat/', buat_rs, name='buat_rs'),
    path('daftar/', daftar_rs, name='daftar_rs'),
    path('update/', update_rs, name='update_rs'),
    path('delete/', delete_rs, name='delete_rs'),
    path('dokter/daftarkan/', daftarkan_dokter, name='daftarkan_dokter'),
    path('dokter/daftar/', daftar_dokter, name='daftar_dokter'),
    path('dokter/update/', update_dokter, name='update_dokter'),
    path('dokter/delete/', delete_dokter, name='delete_dokter'),
    path('admin/daftar/', daftar_admin, name='daftar_admin')
]

rs_cabang/models.py
from django.db import models

# Create your models here.

rs_cabang/forms.py
from django import forms
from django.db import connection


year_choice = ["{0}".format(year) for year in range(1995, 2031)]


class RSForm(forms.Form):
    attrs = {'class': 'form-control'}

    kode_rs = forms.CharField(label='Kode RS Cabang', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    nama = forms.CharField(label='Nama', required=True, max_length=50, widget=forms.TextInput(attrs=attrs))
    tanggal_pendirian = forms.DateField(label='Tanggal Pendirian', required=True, widget=forms.SelectDateWidget(attrs=attrs, years=year_choice))
    jalan = forms.CharField(label='Jalan', required=False, widget=forms.TextInput(attrs=attrs))
    nomor = forms.IntegerField(label='Nomor', required=False, widget=forms.NumberInput(attrs=attrs))
    kota = forms.CharField(label='Kota', required=True, widget=forms.TextInput(attrs=attrs))

    def save(self, commit=True):
        kode_rs = self.cleaned_data.get('kode_rs')
        nama = self.cleaned_data.get('nama')
        tanggal_pendirian = self.cleaned_data.get('tanggal_pendirian')
        jalan = self.cleaned_data.get('jalan')
        nomor = self.cleaned_data.get('nomor')
        kota = self.cleaned_data.get('kota')

        # Save to the database postgresql
        with connection.cursor() as pengguna:
            pengguna.execute('insert into rs_cabang values (%s, %s, %s, %s, %s, %s)',
                             [kode_rs, nama, tanggal_pendirian, jalan, nomor, kota])
            pengguna.close()

    def edit(self, commit=True, kode_rs=None):
        if not kode_rs:
            return

        kode_rs = self.cleaned_data.get('kode_rs')
        nama = self.cleaned_data.get('nama')
        tanggal_pendirian = self.cleaned_data.get('tanggal_pendirian').strftime('%Y-%m-%d')
        jalan = self.cleaned_data.get('jalan')
        nomor = self.cleaned_data.get('nomor')
        kota = self.cleaned_data.get('kota')

        with connection.cursor() as save_rs:
            query = 'update medikago.rs_cabang '
            query += 'set nama=%s, tanggal_pendirian=%s, jalan=%s, nomor=%s, kota=%s '
            query += 'where kode_rs=%s'
            save_rs.execute(query, [nama, tanggal_pendirian, jalan, nomor, kota, kode_rs])
            save_rs.close()


# BEGIN UNGU #

def fetch_to_choices(cursor_fetch):
    choices = []
    choices.append(("-", "-"))
    for item in cursor_fetch:
        choice = (item[0], item[0])
        choices.append(choice)
    return choices

def get_kode_rs():
    with connection.cursor() as cursor:
        cursor.execute('select kode_rs from medikago.rs_cabang')
        query = cursor.fetchall()
        cursor.close()
    return fetch_to_choices(query)

def get_id_dokter():
    with connection.cursor() as cursor:
        cursor.execute('select id_dokter from medikago.dokter')
        query = cursor.fetchall()
        cursor.close()
    return fetch_to_choices(query)

class DaftarkanDokterForm(forms.Form):
    attrs = {'class': 'form-control'}

    kode_rs_choices = get_kode_rs()
    id_dokter_choices = get_id_dokter()

    kode_rs = forms.CharField(label='Kode RS', required=True, widget=forms.Select(choices=kode_rs_choices, attrs=attrs))
    id_dokter = forms.CharField(label='ID Dokter', required=True, widget=forms.Select(choices=id_dokter_choices, attrs=attrs))

    def save(self, commit=True):
        kode_rs = self.cleaned_data.get('kode_rs')
        id_dokter = self.cleaned_data.get('id_dokter')

        with connection.cursor() as cursor:
            cursor.execute('insert into medikago.dokter_rs_cabang values (%s, %s)',
                             [id_dokter, kode_rs])
            cursor.close()
    
    def edit(self, commit=True, id_dokter_old=None, kode_rs_old=None):
        if not (id_dokter_old or kode_rs_old):
            return
        
        kode_rs = self.cleaned_data.get('kode_rs')
        id_dokter = self.cleaned_data.get('id_dokter')

        with connection.cursor() as cursor:
            cursor.execute('update medikago.dokter_rs_cabang set id_dokter=%s, kode_rs=%s where id_dokter=%s and kode_rs=%s', 
                            [id_dokter, kode_rs, id_dokter_old, kode_rs_old])
            cursor.close()

# END UNGU #


KODE_RS_CHOICES = [
    ('RS1', 'RS1'),
    ('RS2', 'RS2'),
    ('RS3', 'RS3'),
    ('RS4', 'RS4'),
    ('RS5', 'RS5')
]

# ID_DOKTER_CHOICES = [
#     ('DOK1', 'DOK1'),
#     ('DOK2', 'DOK2'),
#     ('DOK3', 'DOK3'),
#     ('DOK4', 'DOK4'),
#     ('DOK5', 'DOK5'),
#     ('DOK6', 'DOK6'),
#     ('DOK7', 'DOK7'),
#     ('DOK8', 'DOK8'),
#     ('DOK9', 'DOK9')
# ]

NOMOR_PEGAWAI_CHOICES = [
    ('8ac3c689-74a0-4953-85c6-f45aacead6e2', 'f45aacead6e2'),
    ('e16a9d1a-2141-4470-bb8a-855fbabd36fc', '855fbabd36fc'),
    ('71521487-1c57-4c7e-ac31-d08cc83005b9', 'd08cc83005b9')
]

def get_nomor_pegawai():
    with connection.cursor() as cursor:
        query = "select nomor_pegawai from medikago.administrator"
        cursor.execute(query)
        rows = cursor.fetchall()
        cursor.close()
    
    #print(rows)
    if rows is None:
        print("None")
    return [tuple((item[0], item[0]))
    for item in rows]

def get_kode_rs():
    with connection.cursor() as cursor:
        query = "select kode_rs from medikago.rs_cabang"
        cursor.execute(query)
        rows = cursor.fetchall()
        cursor.close()

    #print(rows)
    if rows is None:
        print("None")
    return [tuple((item[0], item[0]))
    for item in rows]
  

class DaftarkanAdminForm(forms.Form):
    attrs = {'class': 'form-control'}

    daftar_pegawai = get_nomor_pegawai()
    daftar_rs_cabang = get_kode_rs()

    #def __init__(self, data=None, *args, **kwargs):
    #    super(DaftarkanAdminForm, self).__init__(*args, **kwargs)
    #    if data:
    #        self.fields['nomor_pegawai'] = forms.ChoiceField(label="Nomor Pegawai", required=True, choices=data[0])
    #        self.fields['kode_rs'] = forms.ChoiceField(label="Kode RS", required=True, choices=data[1])

    nomor_pegawai = forms.ChoiceField(label='Nomor Pegawai', required=True, choices=daftar_pegawai)
    kode_rs = forms.ChoiceField(label="Kode RS", required=True, choices=daftar_rs_cabang)

    #print(daftar_pegawai)
    #print(daftar_rs_cabang)

    def edit(self, commit=True):
        nomor_pegawai = self.cleaned_data.get('nomor_pegawai')
        kode_rs = self.cleaned_data.get('kode_rs')

        print(kode_rs)

        with connection.cursor() as edit_admin:
            query = "update medikago.administrator "
            query += "set kode_rs = %s where nomor_pegawai = %s"
            edit_admin.execute(query, [kode_rs, nomor_pegawai])
            edit_admin.close()

rs_cabang/views.py
from django.db import connection
from django.shortcuts import redirect, render
from rs_cabang.forms import *

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


def fetch_rs():
    with connection.cursor() as get_all_rs:
        get_all_rs.execute('select * from medikago.rs_cabang')
        result = dictfetchall(get_all_rs)
        get_all_rs.close()
    return result


def rs_is_not_exist(kode_rs=None):
    if kode_rs == None:
        return

    with connection.cursor() as rs_exist:
        rs_exist.execute('select * from medikago.rs_cabang where kode_rs=%s', [kode_rs])
        rs = rs_exist.fetchone()
        rs_exist.close()
    return rs is None


# Create your views here.
def buat_rs(request):
    form = RSForm

    context = {
        'page_title': 'Buat RS',
        'form': form
    }

    if request.method == "POST":
        form = form(request.POST)
        if form.is_valid():
            if rs_is_not_exist(request.POST.get('kode_rs')):
                kode_rs = form.cleaned_data.get('kode_rs')
                nama = form.cleaned_data.get('nama')
                tanggal_pendirian = form.cleaned_data.get('tanggal_pendirian').strftime('%Y-%m-%d')
                jalan = form.cleaned_data.get('jalan')
                nomor = form.cleaned_data.get('nomor')
                kota = form.cleaned_data.get('kota')

                with connection.cursor() as buat_rs:
                    buat_rs.execute('insert into medikago.rs_cabang values (%s, %s, %s, %s, %s, %s)',
                                    [kode_rs, nama, tanggal_pendirian, jalan, nomor, kota]
                                    )
                    buat_rs.close()

                return redirect('rs_cabang:daftar_rs')
            else:
                context['error'] = 'Sudah ada Rumah Sakit dengan Kode RS: ' + request.POST.get('kode_rs')
                context['form'] = form
                return render(request, 'rs_cabang/buat_rs.html', context)

    return render(request, 'rs_cabang/buat_rs.html', context)


def daftar_rs(request):
    rs_tuple = fetch_rs()

    context = {
        'page_title': 'Daftar RS',
        'rs_dict': rs_tuple
    }

    return render(request, 'rs_cabang/daftar_rs.html', context)


def update_rs(request):
    if request.method == 'GET':
        return redirect('rs_cabang:daftar_rs')

    form = RSForm

    context = {
        'page_title': 'Update RS Cabang',
        'form': form
    }

    if request.method == 'POST':
        if request.POST.get('edit') == 'true':
            with connection.cursor() as get_rs:
                get_rs.execute('select * from medikago.rs_cabang where kode_rs=%s', [request.POST.get('kode_rs')])
                rumah_sakit_query = get_rs.fetchone()
                get_rs.close()

            rumah_sakit = {
                'kode_rs': rumah_sakit_query[0],
                'nama': rumah_sakit_query[1],
                'tanggal_pendirian': rumah_sakit_query[2],
                'jalan': rumah_sakit_query[3],
                'nomor': rumah_sakit_query[4],
                'kota': rumah_sakit_query[5]
            }

            form = form(rumah_sakit)
            context['form'] = form
            context['kode_rs'] = rumah_sakit_query[0]

            return render(request, 'rs_cabang/update_rs.html', context)
        else:
            form = form(request.POST)
            if form.is_valid():
                form.edit(kode_rs=request.POST.get('kode_rs'))
                return redirect('rs_cabang:daftar_rs')
    return render(request, 'rs_cabang/update_rs.html', context)


def delete_rs(request):
    if request.method == 'POST':
        kode_rs = request.POST.get('kode_rs')
        if kode_rs:
            with connection.cursor() as delete_rs:
                delete_rs.execute('delete from medikago.rs_cabang where kode_rs=%s', [kode_rs])
                delete_rs.close()
    return redirect("rs_cabang:daftar_rs")

# BEGIN UNGU #

def daftarkan_dokter(request):
    if request.session.get('user').get('role') != 'Administrator':
        return redirect('home')

    context = {
        'page_title': 'Buat Sesi Konsultasi'
    }

    form = DaftarkanDokterForm
    context['form'] = form

    if request.method == 'POST':
        form = form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('rs_cabang:daftar_dokter')
        else:
            context['form'] = form
            return render(request, 'rs_cabang/daftarkan_dokter.html', context)
    
    return render(request, 'rs_cabang/daftarkan_dokter.html', context)

def get_daftar_dokter():
    with connection.cursor() as cursor:
        cursor.execute('select * from medikago.dokter_rs_cabang order by kode_rs')
        list_daftar_dokter = dictfetchall(cursor)
        cursor.close()
    return list_daftar_dokter

def daftar_dokter(request):
    context = {
        'page_title': 'Daftar Dokter RS Cabang'
    }

    user = request.session.get('user')
    role = user.get('role')

    context['daftar_dokter'] = get_daftar_dokter()

    return render(request, 'rs_cabang/daftar_dokter.html', context)

def update_dokter(request):
    if request.method == 'GET':
        return redirect('rs_cabang:daftar_dokter')
    
    context = {
        'page_title': 'Update Dokter RS Cabang'
    }

    form = DaftarkanDokterForm
    context['form'] = form

    if request.method == "POST":
        id_dokter_old = request.POST.get('id_dokter_old')
        kode_rs_old = request.POST.get('kode_rs_old')
        if request.POST.get('edit') == 'true':
            with connection.cursor() as cursor:
                cursor.execute('select * from medikago.dokter_rs_cabang where id_dokter=%s and kode_rs=%s', 
                                [id_dokter_old, kode_rs_old])
                dokter_rs_cabang_query = cursor.fetchone()
                cursor.close()

            dokter_rs_cabang = {
                'id_dokter': dokter_rs_cabang_query[0],
                'kode_rs': dokter_rs_cabang_query[1],
            }

            form = form(dokter_rs_cabang)
            context['form'] = form
            context['id_dokter'] = dokter_rs_cabang_query[0]
            context['kode_rs'] = dokter_rs_cabang_query[1]
            context['id_dokter_old'] = id_dokter_old
            context['kode_rs_old'] = kode_rs_old

            return render(request, 'rs_cabang/update_dokter.html', context)
        else:
            form = form(request.POST)
            if form.is_valid():
                form.edit(id_dokter_old=id_dokter_old, kode_rs_old=kode_rs_old)
                return redirect('rs_cabang:update_dokter')
    return render(request, 'rs_cabang/update_dokter.html', context)

def delete_dokter(request):
    if request.method == 'POST':
        id_dokter = request.POST.get('id_dokter')
        kode_rs = request.POST.get('kode_rs')
        with connection.cursor() as cursor:
            cursor.execute('delete from medikago.dokter_rs_cabang where id_dokter=%s and kode_rs=%s',
                            [id_dokter, kode_rs])
            cursor.close()
    return redirect("rs_cabang:daftar_dokter")

# END UNGU #

def daftar_admin(request):

    form = DaftarkanAdminForm()

    form.fields['nomor_pegawai'].widget.choices = get_nomor_pegawai()
    form.fields['kode_rs'].widget.choices = get_kode_rs()

    context = {
        'page_title': 'Daftar Administrator',
        'form': form
    }

    if request.method == 'POST':
        form=DaftarkanAdminForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            nomor_pegawai = form.cleaned_data['nomor_pegawai']
            kode_rs = form.cleaned_data['kode_rs']
            form.edit()
            form.fields['nomor_pegawai'].widget.choices = get_nomor_pegawai()
            form.fields['kode_rs'].widget.choices = get_kode_rs()
            return render(request, 'rs_cabang/daftar_admin.html', context)
        else:
            context[ 'form' ] = form
            form.fields['nomor_pegawai'].widget.choices = get_nomor_pegawai()
            form.fields['kode_rs'].widget.choices = get_kode_rs()
            return render(request, 'rs_cabang/daftar_admin.html', context)
                    
    return render(request, 'rs_cabang/daftar_admin.html', context)

rs_cabang/templates/rs_cabang/buat_rs.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='container'>
    <div class='d-flex justify-content-center align-items-center my-3'>
        <div class='d-flex flex-column'>
            <div class='text-center my-3'><h2>Buat RS Cabang</h2></div>
            <div class='d-flex justify-content-center my-2'>
                <div><span style="color: #dc3545;">{{ error }}</span></div>
            </div>
            <div class='container'>
                <form method='POST'>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class='form-group'>
                            <b>{{ field.label_tag }}</b>
                            <div class='d-flex'>
                                {{ field }}
                            </div>
                            {% if field.errors %}
                                <strong style="color: red;">{{ field.errors }}</strong>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary float-right">Submit</button>
                </form>
            </div>
        </div>
    </div>    
</div>
{% endblock content %}

rs_cabang/templates/rs_cabang/daftar_admin.html
{% extends 'basdat59/base.html' %}

{% block content %}
<!-- KUNING -->
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Daftarkan Admin</h2>
    </div>
    <div>
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class='form-group'>
                <b>{{ field.label_tag }}</b>
                <div>
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-outline-primary my-3">Daftar</button>
        </form>
    </div>
</div>
{% endblock content %}

rs_cabang/templates/rs_cabang/daftar_dokter.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Daftar Dokter</h2>
    </div>
    <div>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Kode RS Cabang</th>
                    <th scope="col">ID Dokter</th>
                    {% if request.session.user.role == 'Administrator' %}
                    <th scope="col">Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for dokter_rs_cabang in daftar_dokter %}
                <tr>
                    <td>{{ dokter_rs_cabang.kode_rs }}</td>
                    <td>{{ dokter_rs_cabang.id_dokter }}</td>
                    {% if request.session.user.role == 'Administrator' %}
                    <td class='align-middle'>
                        <div class='d-flex justify-content-center'>
                            <div class='mr-1'>
                                <form action="{% url 'rs_cabang:update_dokter' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="id_dokter_old" value="{{ dokter_rs_cabang.id_dokter }}" hidden>
                                    <input type="hidden" name="kode_rs_old" value="{{ dokter_rs_cabang.kode_rs }}" hidden>
                                    <input type="hidden" name="edit" value="true" hidden>
                                    <button type="submit" class="btn btn-primary" title="Update">Update</button>
                                </form>
                            </div>
                            <div>
                                <form action="{% url 'rs_cabang:delete_dokter' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="id_dokter" value="{{ dokter_rs_cabang.id_dokter }}" hidden>
                                    <input type="hidden" name="kode_rs" value="{{ dokter_rs_cabang.kode_rs }}" hidden>
                                    <button type="submit" class="btn btn-outline-danger" title="Delete">Delete</button>
                                </form>
                            </div>
                        </div>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    const table = document.querySelector('table');

    let headerCell = null;

    for (let row of table.rows) {
    const firstCell = row.cells[0];
    
    if (headerCell === null || firstCell.innerText !== headerCell.innerText) {
        headerCell = firstCell;
    } else {
        headerCell.rowSpan++;
        firstCell.remove();
    }
    }
</script>
{% endblock script %}

rs_cabang/templates/rs_cabang/daftar_rs.html
{% extends 'basdat59/base.html' %}

{% block style %}
<style>
    th, td, a {
        vertical-align: middle !important;
        text-align: center;
    }
</style>
{% endblock style %}

{% block content %}
<div class='container'>
    <div class='col-md d-flex justify-content-center flex-column'>
        {% if rs_dict %}
        <div class='my-4 d-flex justify-content-center'>
            <h2><b>Daftar RS Cabang</b></h2>
        </div>
        <div class='table-responsive'>
            <table class="table table-striped">
                <thead class='thead-dark'>
                    <tr>
                        <th scope="col">Kode RS</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Tanggal Pendirian</th>
                        <th scope="col">Jalan</th>
                        <th scope="col">Nomor</th>
                        <th scope="col">Kota</th>
                        {% if request.session.user.role == 'Administrator' %}
                        <th scope="col">Action</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for rs_cabang in rs_dict %}
                    <tr>
                        <td>{{ rs_cabang.kode_rs }}</td>
                        <td>{{ rs_cabang.nama }}</td>
                        <td>{{ rs_cabang.tanggal_pendirian }}</td>
                        <td>{{ rs_cabang.jalan }}</td>
                        <td>{{ rs_cabang.nomor }}</td>
                        <td>{{ rs_cabang.kota }}</td>
                        {% if request.session.user.role == 'Administrator' %}
                        <td class='align-middle'>
                            <div class='d-flex justify-content-center'>
                                <div class='mr-1'>
                                    <form action="{% url 'rs_cabang:update_rs' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="kode_rs" value="{{ rs_cabang.kode_rs }}" hidden>
                                        <input type="hidden" name="edit" value="true" hidden>
                                        <button type="submit" class="btn btn-primary" title="edit">Edit</button>
                                    </form>
                                </div>
                                <div>
                                    <form action="{% url 'rs_cabang:delete_rs' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="kode_rs" value="{{ rs_cabang.kode_rs }}">
                                        {% if rs_cabang.kode_rs != 'RS1' %}
                                        <button type="submit" class="btn btn-danger" title="edit">X</button>
                                        {% endif %}
                                    </form>
                                </div>
                            </div>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>       
        </div>
        {% else %}
        <div class='d-flex my-2'>
            <div>
                <span>Tidak ada Rumah Sakit Cabang yang terdaftar!</span>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

rs_cabang/templates/rs_cabang/daftarkan_dokter.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Daftarkan Dokter</h2>
    </div>
    <div>
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class='form-group'>
                <b>{{ field.label_tag }}</b>
                <div>
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-outline-primary my-3">Daftar</button>
        </form>
    </div>
</div>
{% endblock content %}

rs_cabang/templates/rs_cabang/update_dokter.html
{% extends 'basdat59/base.html' %}

{% block content %}
<div class='d-flex flex-column align-items-center my-5'>
    <div class='my-3'>
        <h2>Update Dokter</h2>
    </div>
    <div>
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <b>{{ field.label_tag }}</b>
                <div class="d-flex">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <input type="hidden" name="id_dokter_old" id="id_dokter_p" value="{{ id_dokter_old }}" hidden>
            <input type="hidden" name="kode_rs_old" id="kode_rs_p" value="{{ kode_rs_old }}" hidden>
            <input type="hidden" name="edit" value="false" hidden>
            <div>
                <div id="message"></div>
                <button type="submit" class="btn btn-outline-primary my-3" id="update_button">Update</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function() {
        $("#id_id_dokter").change(function(event) {
            $("#message").html("");
            
            let id_dokter = $(this).val();
            let id_dokter_p = $("#id_dokter_p").val();
            
            if (id_dokter == "-") {
                $("#message").html("ID Dokter '-' tidak valid.");
                $("#message").css('color', '#dc3545');
                $("#update_button").attr("disabled", "True");
            } else if (id_dokter == id_dokter_p) {
                $("#id_kode_rs").removeAttr("disabled");
                $("#message").html("ID Dokter tidak berubah.");
                $("#message").css('color', '#dc3545');
                $("#update_button").attr("disabled", "True")
            } else {
                $("#id_kode_rs").attr("disabled", "True");
                $("#update_button").removeAttr("disabled");
            }
        });
        $("#id_kode_rs").change(function(event) {
            $("#message").html("");
            
            let kode_rs = $(this).val();
            let kode_rs_p = $("#kode_rs_p").val();
            
            if (kode_rs == "-") {
                $("#message").html("Kode RS '-' tidak valid.");
                $("#message").css('color', '#dc3545');
                $("#update_button").attr("disabled", "True");
            } else if (kode_rs == kode_rs_p) {
                $("#id_id_dokter").removeAttr("disabled");
                $("#message").html("Kode RS tidak berubah.");
                $("#message").css('color', '#dc3545');
                $("#update_button").attr("disabled", "True")
            } else {
                $("#id_id_dokter").attr("disabled", "True");
                $("#update_button").removeAttr("disabled");
            }
        });
    });
</script>
{% endblock script %}

rs_cabang/templates/rs_cabang/update_rs.html
{% extends 'basdat59/base.html' %}

{% block style %}
<style>
    th, td, a {
        vertical-align: middle !important;
        text-align: center;
    }
</style>
{% endblock style %}

{% block content %}
<div class='container'>
    <div class='d-flex justify-content-center align-items-center my-3'>
        <div class='d-flex flex-column'>
            <div class='text-center my-3'><h2>Update RS Cabang</h2></div>
            <div>
                <form method='POST'>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class='form-group'>
                            <b>{{ field.label_tag }}</b>
                            <div class='d-flex'>
                            {% if 'Kode' in field.label %}
                                <input type="text" name="{{ field.name }}" value="{{ field.value }}" class="form-control" maxlength="50" required="" id="id_kode_rs" disabled>
                            {% else %}
                                {{ field }}
                            {% endif %}
                            </div>
                            {% if field.errors %}
                                <strong style="color: red;">{{ field.errors }}</strong>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="hidden" name="kode_rs" value="{{ kode_rs }}" hidden>
                    <input type="hidden" name="edit" value="false" hidden>
                    <button type="submit" class="btn btn-primary float-right">Submit</button>
                </form>
            </div>
        </div>
    </div>    
</div>
{% endblock content %}